name: Get Codex

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.gitattributes'
      - 'LICENSE*'
  workflow_dispatch:

env:
  folder: site

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Prepare file
        run: |
          mkdir ${{ env.folder }}
          find . -type f \
            -maxdepth 1 \
            -name "*.*" \
            ! -name '*.md' \
            ! -name ".git*" \
            ! -name "LICENSE*" \
            -exec cp {} ${{ env.folder }} \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.folder }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
